// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tema_1
    (
        init => init
        upgrade => upgrade
        setFootballCourtCost => set_football_court_cost
        createFootballSlot => create_football_slot
        getFootballFieldManager => football_field_manager_address
        getFootballCourtCost => football_court_cost
        getParticipants => participants
        getReservedSlot => reserved_slot
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
